# vim:ts=2:sw=2:sts=2:et:ai

- hosts: bitwarden
  strategy: free
  remote_user: root
  tasks:

# - name: Install Docker GPG key
#   ansible.builtin.command: "curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg"
#   ansible.builtin.get_url:
#     url: https://download.docker.com/linux/debian/gpg

  - name: Install Docker GPG key
    ansible.builtin.apt_key:
      url: https://download.docker.com/linux/debian/gpg
      state: present

  - name: Add docker repo
    ansible.builtin.copy:
      src: files/etc/apt/sources.list.d/docker.list
      dest: /etc/apt/sources.list.d/docker.list

  - name: "Do an apt full-upgrade"
    ansible.builtin.apt:
      update_cache: yes
      upgrade: dist
      autoremove: yes

  - name: Install the bitwarden prerequisites
    ansible.builtin.apt:
      name:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common
        - docker-ce
        - docker-ce-cli
        - containerd.io
      state: latest
