# vim:ts=2:sw=2:sts=2:et:ai:fdm=marker

- hosts: vmer
  strategy: free
  remote_user: root
  tasks:
  - name: apt-get dist-upgrade
    ansible.builtin.apt:
      update_cache: yes
      upgrade: dist

  - name: Reboot
    ansible.builtin.reboot:
      reboot_timeout: 60
