# vim:ts=2:sw=2:sts=2:et:ai

- hosts: freeipa
  strategy: free

  remote_user: root
  tasks:
  - name: "Do an apt full-upgrade"
    ansible.builtin.apt:
      update_cache: yes
      name: restic
      state: latest

  - name: Install zabbix, postgres and apache
    apt:
      name:
        - postgresql-13
        - apache2
        - zabbix-server-pgsql

