- hosts: gluster
  tasks:
  - name: apt-get full-upgrade
    ansible.builtin.apt:
      update_cache: yes
      upgrade: dist
      autoremove: yes
  - name: Install gluster server stuff
    ansible.builtin.apt:
      name:
        - glusterfs-server
  - name: Enable and start glusterd
    ansible.builtin.systemd:
      name: glusterd
      state: started
      enabled: yes
  - name: Enable IPv6 for glusterfs
    ansible.builtin.lineinfile:
      path: /etc/glusterfs/glusterd.vol
      regexp: 'option transport\.address-family'
      line: '    option transport.address-family inet6'
    notify:
    - restart glusterd
  - name: Allow traffic from other cluster members
    community.general.ufw:
      rule: allow
      src: '{{ item }}'
    loop:
      - 2a01:79c:cebe:d8d0:300::22
      - 2a01:79c:cebe:d8d0:300::23
      - 2a01:79c:cebe:d8d0:300::24
      - 2a01:79c:cebe:d8d0:300::29
  - name: Add hostnames+IPs to /etc/hosts
    ansible.builtin.blockinfile:
      path: /etc/hosts
      block: |
        2a01:79c:cebe:d8d0:300::22	glusterfs01.karlsbakk.net glusterfs01
        2a01:79c:cebe:d8d0:300::23	glusterfs02.karlsbakk.net glusterfs02
        2a01:79c:cebe:d8d0:300::24	glusterfs03.karlsbakk.net glusterfs03
        2a01:79c:cebe:d8d0:300::29	rocky-gluster-client.karlsbakk.net rocky-gluster-client
  handlers:
    - name: restart glusterd
      service:
        name: glusterd
        state: restarted
