# vim:ts=2:sw=2:sts=2:et:ai

- hosts: homeassistant
  strategy: free
  remote_user: root
  tasks:
  - name: Make sure group homeassistant exists
    ansible.builtin.group:
      name: homeassistant
      state: present
  - name: Make sure user homeassistant exists
    ansible.builtin.user:
      name: homeassistant
      state: present
      comment: "Home Assistant system user"
      group: homeassistant
      groups: dialout,gpio,i2c
  - name: Create homeassistant system dir
    file:
      path: /home/homeassistant/.homeassistant
      mode: 0750
      owner: homeassistant
      group: homeassistant
      state: directory
# - name: Install the normal stuff
#   ansible.builtin.apt:
#     name:
#       - dummy
#     update_cache: yes
#     state: latest
# - name: UFW - Allow SSH and HTTP(S)
#   ufw:
#     rule: allow
#     port: '{{ item.port  }}'
#     comment: '{{ item.comment  }}'
#   with_items:
#     - { port: "22", comment: "Allow SSH" }
#     - { port: "80", comment: "Allow HTTP" }
#     - { port: "443", comment: "Allow HTTPS" }

