# vim:ts=2:sw=2:sts=2:et:ai

- hosts: ipv6change
  strategy: free
  vars:
    old_prefix: '2a01:79c:cebf:61e4:'
    new_prefix: '2a01:79c:cebe:d8d0:'

  remote_user: root
  tasks:
  - name: "Change IPv6 prefix - address"
    ansible.builtin.lineinfile:
      path: /tmp/interfaces
      regexp: '^(\s+address\s+){{ old_prefix }}(.*)$'
      line: '\1{{ new_prefix }}\2'
      backrefs: yes

  - name: "Change IPv6 prefix - gateway"
    ansible.builtin.lineinfile:
      path: /tmp/interfaces
      regexp: '^(\s+gateway\s+){{ old_prefix }}(.*)$'
      line: '\1{{ new_prefix }}\2'
      backrefs: yes

