# vim:ts=2:sw=2:sts=2:et:ai

- hosts: kopano
  strategy: free

  remote_user: root
  vars:
    kopano_packages:
    - kopano-server
    - kopano-webapp-nginx
  tasks:
  - name: "Do an apt full-upgrade"
    apt:
      update_cache: yes

  - name: "Install kopano packages"
    apt:
      name: "{{ kopano_packages }}"
      update_cache: yes
      state: latest
