- hosts: vmer
  strategy: free
  vars:
    http_port: 80
    max_clients: 200
    locales:
      - en_GB.UTF-8
      - en_US.UTF-8
      - nb_NO.UTF-8
      - nn_NO.UTF-8
      - no_NO.UTF-8
    language:
      - en_GB:en
      - en_US:en
      - nb_NO:no
      - nn_NO:no
      - no_NO:no

  remote_user: root
  tasks:
  - name: Set timezone to Europe/Oslo
    ansible.builtin.file:
      src: /usr/share/zoneinfo/Europe/Oslo
      dest: /etc/localtime
      state: link

  - name: Generate the selected locales
    community.general.locale_gen:
      name: "{{ item }}"
      state: present
    loop: "{{ locales }}"
    notify: "rebuild locales database"
  
  - name: Set the default locale
    ansible.builtin.lineinfile:
      dest: /etc/default/locale
      regexp: "^LANG="
      line: "LANG={{ locale }}"
    notify: "rebuild locales database"

  # # this will always report as "changed"
  # # why don't we set LC_TIME the same way as LANG above?
  # - name: Set LC_TIME to international standard date/time notation
  #   ansible.builtin.command: localectl set-locale LC_TIME="{{ LC_time }}"
  #   notify: "rebuild locales database"

  - name: "Set LC_TIME to {{ LC_time }}"
    ansible.builtin.lineinfile:
      dest: /etc/default/locale
      regexp: "^LC_TIME="
      line: "LC_TIME={{ LC_time }}"
    notify: "rebuild locales database"

# NOTE: changes won't take effect until logout/login (no effect in the current session)
# it does however take effect in new sessions (via ssh, for example) and
# new sessions for other users than the currently logged in user
# I have not found a way to make changes take effect immediately on Ubuntu
