# vim:ts=2:sw=2:sts=2:et:ai

- hosts: kykelipi
  strategy: free
  vars:
    http_port: 80
    max_clients: 200
  remote_user: root
  tasks:
  - name: Install sysstat, vim, git, etckeeper
    apt:
      name: sysstat,vim,git,etckeeper
      update_cache: yes
      state: latest
  - name: Enable sysstat
    lineinfile:
      path: /etc/default/sysstat
      regexp: '^ENABLED='
      line: 'ENABLED="true"'
    notify:
    - restart sysstat
  - name: ensure sysstat is running
    service:
      name: sysstat
      state: started

  - name: update bashrc
    blockinfile:
      dest: /root/.bashrc
      block: |
        # Ansible was here!!!!
        export LS_OPTIONS='--color=auto'
        eval "`dircolors`"
        alias ls='ls $LS_OPTIONS'
        alias l='ls $LS_OPTIONS -l'

        set -o vi

  - name: update /etc/vim/vimrc.local
    blockinfile:
      dest: /etc/vim/vimrc.local
      create: yes
      marker: '" {mark} ANSIBLE MANAGED BLOCK'
      block: |
        syntax on
        if has("autocmd")
          au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
        endif

        if has("autocmd")
          filetype plugin indent on
        endif

        set background=dark
        set incsearch
        set modeline
        set foldmethod=marker

        set mouse=
        set ttymouse=

  - name: set timezone to Europe/Oslo
    timezone:
      name: Europe/Oslo
  handlers:
    - name: restart sysstat
      service:
        name: sysstat
        state: restarted
