# vim:ts=2:sw=2:sts=2:et:ai

- hosts: servere
  strategy: free

  remote_user: root
  vars:
    custom_packages:
    - apt-transport-https
    - autoconf
    - automake
    - build-essential
    - etckeeper
    - fail2ban
    - finger
    - git
    - htop
    - locales-all
    - lshw
    - mlocate
    - sudo
    - sysstat
    - tmux
    - tree
    - tshark
    - ufw
    - unattended-upgrades
    - vim
    - zabbix-agent
    vimrc: |

        syntax on
        set background=dark
        set incsearch
        set modeline
        set modelines=5
        set nohlsearch
        set ruler

        if has("autocmd")
          au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
          filetype plugin indent on
        endif

        au BufNewFile,BufRead *.gcode setf gcode
        let g:autoclose_on = 0
        let g:AutoPairs = {}
  tasks:
  - name: "Do an apt dist-upgrade"
    apt:
      update_cache: yes
      upgrade: dist

  - name: "Install various packages"
    apt:
      name: "{{ custom_packages }}"
      update_cache: yes
      state: latest

  - name: "Enable unattended upgrades for everything except 'proposed'"
    lineinfile:
      path: /etc/apt/apt.conf.d/50unattended-upgrades
      regex: 'origin=Debian,codename=\${distro_codename}-updates'
      line: "        \"origin=Debian,codename=${distro_codename}-updates\";"

  - name: "Set email address for unattended upgrades report"
    lineinfile:
      path: /etc/apt/apt.conf.d/50unattended-upgrades
      regex: 'Unattended-Upgrade::Mail '
      line: 'Unattended-Upgrade::Mail "roy@karlsbakk.net";'

  - name: "Set when to send unattended upgrades report"
    lineinfile:
      path: /etc/apt/apt.conf.d/50unattended-upgrades
      regex: 'Unattended-Upgrade::MailReport '
      line: 'Unattended-Upgrade::MailReport "only-on-error"'

  - name: "Turn on unattended upgrades"
    ansible.builtin.blockinfile:
      path: "/etc/apt/apt.conf.d/20auto-upgrades"
      create: yes
      marker: "// {mark} ANSIBLE MANAGED BLOCK"
      block: |
        // Actually enable unattended upgrades
        APT::Periodic::Update-Package-Lists "1";
        APT::Periodic::Unattended-Upgrade "1";

  - name: "Set editor"
    command: update-alternatives --set editor /usr/bin/vim.basic

  - name: Tell zabbix_agent about our server passive server
    lineinfile:
      path: /etc/zabbix/zabbix_agentd.conf
      regexp: '^Server='
      line: 'Server=zabbix.karlsbakk.net'

  - name: Tell zabbix_agent about our server active server
    lineinfile:
      path: /etc/zabbix/zabbix_agentd.conf
      regexp: '^ServerActive='
      line: 'ServerActive=zabbix.karlsbakk.net'

  - name: Enable sysstat
    lineinfile:
      path: /etc/default/sysstat
      regexp: '^ENABLED='
      line: ENABLED="true"

  - name: ensure sysstat is running
    service:
      name: sysstat
      state: started

# ssh authorization
  - name: Create ssh dir for root
    file:
      path: /root/.ssh
      mode: 0700
      owner: root
      group: root
      state: directory

  - name: Ensure group 'roy' exists with correct gid
    ansible.builtin.group:
      name: roy
      state: present
      gid: 1000

  - name: Add the user 'roy' with a specific uid and a primary group of 'roy'
    ansible.builtin.user:
      name: roy
      group: roy
      groups: ssh,adm
      comment: Roy Sigurd Karlsbakk
      uid: 1000
      generate_ssh_key: yes

  - name: Create ssh dir for roy
    file:
      path: /home/roy/.ssh
      mode: 0700
      owner: roy
      group: roy
      state: directory

  - name: "Add roy to sudoers"
    user:
      name: "roy"
      groups: "sudo"
      append: yes

  - name: Add relevant keys to /root/.ssh/authorized_keys
    ansible.builtin.blockinfile:
      path: "/root/.ssh/authorized_keys"
      create: yes
      block: |
        ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDHgvHmjGfZgw1tT3zC88dPWEH+mxykfGvE+S8atcfdAl/3Zjcp48UGk0otL4v+9rdIo1/PwOL/aUR3D19GyQtWycO32wyNNr6N5DQNo64YAfI6unxLceiRWqWEEhEHSfKbVVjUyQllhjhzoyLxQ7OMBVVdIbTFRqAYIKXnLDD9uuC6fpcGTGDEc28Y3gz1Q1i3D55bIXF5Usd1BSP3D2FRgjDRX+0xGCvavWG548p1Y0tbbWbL+t+gXbHwRQtg2eqcd5nM1QdS0EX/r/9eOu715UMtiSk+NW6I8PzJN/KmO9PxJ9KLKOtBYfx4kXGVPk3e4O8ZpExHa4e4nzwYibCv roysk@oslomet.no
        ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAvlfCc6RoDq7jzSy1svNMPcusSkCMefCZE6aT12I7KgPOXUdvGfPqexZhMEO0ooW9+hIwa0NXozEB39Wl8QonsMNtkaJ68KnLAzh6acEFfhzBlSMgjh8EFErD9Td3MFOEZlPApwgIc4H1P7pmhAri3rYN2kWkcD1M2yATMsa7g7PSM9Lq4ol65lf7pFtk/KP6jW5g9HCR0lXllX1RCMCv3iozd8eUApatP3SmkY4UIChPrhefbOrdDIevTxjL7LKXo8Ojv3qbu2H34NdI+y6JDZh9SWJZNIE0bSj9FnO0ZlYXigL2z+xgqfpNSMXnuYc0/zPyot0dLYLFRFhSBjUYnQ== roy@karlsbakk.net
      owner: root
      group: root

  - name: Add relevant keys to /home/roy/.ssh/authorized_keys
    ansible.builtin.blockinfile:
      # ansible har lookup('env','HOME') og om du bruker become så kan du kjøre den for enhver bruker
      # https://stackoverflow.com/questions/33343215/how-to-get-an-arbitrary-remote-users-home-directory-in-ansible
      # men kanskje bruke variabler og la ansible bestemme hvordan det skal se ut
      path: "{{ item.homedir }}/.ssh/authorized_keys"
      create: yes
      owner: "{{ item.username }}"
      group: "{{ item.username }}"
      block: |
        ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDHgvHmjGfZgw1tT3zC88dPWEH+mxykfGvE+S8atcfdAl/3Zjcp48UGk0otL4v+9rdIo1/PwOL/aUR3D19GyQtWycO32wyNNr6N5DQNo64YAfI6unxLceiRWqWEEhEHSfKbVVjUyQllhjhzoyLxQ7OMBVVdIbTFRqAYIKXnLDD9uuC6fpcGTGDEc28Y3gz1Q1i3D55bIXF5Usd1BSP3D2FRgjDRX+0xGCvavWG548p1Y0tbbWbL+t+gXbHwRQtg2eqcd5nM1QdS0EX/r/9eOu715UMtiSk+NW6I8PzJN/KmO9PxJ9KLKOtBYfx4kXGVPk3e4O8ZpExHa4e4nzwYibCv roysk@oslomet.no
        ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAvlfCc6RoDq7jzSy1svNMPcusSkCMefCZE6aT12I7KgPOXUdvGfPqexZhMEO0ooW9+hIwa0NXozEB39Wl8QonsMNtkaJ68KnLAzh6acEFfhzBlSMgjh8EFErD9Td3MFOEZlPApwgIc4H1P7pmhAri3rYN2kWkcD1M2yATMsa7g7PSM9Lq4ol65lf7pFtk/KP6jW5g9HCR0lXllX1RCMCv3iozd8eUApatP3SmkY4UIChPrhefbOrdDIevTxjL7LKXo8Ojv3qbu2H34NdI+y6JDZh9SWJZNIE0bSj9FnO0ZlYXigL2z+xgqfpNSMXnuYc0/zPyot0dLYLFRFhSBjUYnQ== roy@karlsbakk.net
    with_items:
      - { username: 'roy', homedir: '/home/roy' }

  - name: update /root/.vimrc
    ansible.builtin.blockinfile:
      dest: /root/.vimrc
      owner: root
      group: root
      create: yes
      marker: "\" {mark} ANSIBLE MANAGED BLOCK"
      block: |
        {{ vimrc }}
#     block: |
#       syntax on
#       set background=dark
#       set incsearch
#       set modeline
#       set nohlsearch
#       set ruler

  - name: update /root/.tmux.conf
    ansible.builtin.blockinfile:
      dest: /root/.tmux.conf
      create: yes
      block: |
        set -g prefix C-a
        unbind-key C-b
        bind-key C-a send-prefix
        setw -g mode-keys vi
  - name: update /root/.bashrc
    ansible.builtin.blockinfile:
      dest: /root/.bashrc
      owner: root
      group: root
      create: yes
      block: |
        # Ansible was here!!!!
        export LS_OPTIONS='--color=auto'
        eval "`dircolors`"
        alias ls='ls $LS_OPTIONS'
        alias l='ls $LS_OPTIONS -l'

        export EDITOR='vim'
        set -o vi

  - name: update .bashrc
    ansible.builtin.blockinfile:
      dest: "/home/{{ item }}/.bashrc"
      owner: "{{ item }}"
      group: "{{ item }}"
      create: yes
      block: |
        export LS_OPTIONS='--color=auto'
        eval "`dircolors`"
        alias ls='ls $LS_OPTIONS'
        alias l='ls $LS_OPTIONS -l'

        export EDITOR='vim'
        set -o vi
    with_items:
      - 'roy'

  - name: "update /home/{{ item }}/.vimrc"
    ansible.builtin.blockinfile:
      dest: "/home/{{ item }}/.vimrc"
      owner: "{{ item }}"
      group: "{{ item }}"
      create: yes
      marker: "\" {mark} ANSIBLE MANAGED BLOCK"
      block: |
        syntax on
        set modeline
        set background=dark
        set incsearch
        set nohlsearch
        set ruler
        set mouse=
        set ttymouse=
    with_items:
      - 'roy'

  - name: update /root/.inputrc
    ansible.builtin.blockinfile:
      dest: /root/.inputrc
      owner: "root"
      group: "root"
      create: yes
      block: |
        set editing-mode vi

  - name: update /home/{{ item }}/.inputrc
    ansible.builtin.blockinfile:
      dest: "/home/{{ item }}/.inputrc"
      owner: "{{ item }}"
      group: "{{ item }}"
      create: yes
      block: |
        set editing-mode vi
    with_items:
      - 'roy'

  - name: update /root/.vimrc
    ansible.builtin.blockinfile:
      dest: /home/root/.vimrc
      owner: root
      group: root
      create: yes
      marker: "\" {mark} ANSIBLE MANAGED BLOCK"
      block: |
        syntax on
        set modeline
        set background=dark
        set incsearch
        set foldmethod=marker
        set mouse=
        set ttymouse=

  - name: set timezone to Europe/Oslo
    timezone:
      name: Europe/Oslo

  - name:
    git_config:
      name: user.email
      repo: /etc
      scope: local
      value: roy@karlsbakk.net

  - name:
    git_config:
      name: user.name
      repo: /etc
      scope: local
      value: 'Roy Sigurd Karlsbakk'

