# vim:ts=2:sw=2:sts=2:et:ai

- hosts: smtp
  strategy: free
  remote_user: root
  tasks:
  - name: "Do an apt full-upgrade"
    ansible.builtin.apt:
      update_cache: yes
      upgrade: dist
      autoremove: yes

  - name: Install the bitwarden prerequisites
    ansible.builtin.apt:
      name:
        - postfix
      state: latest

  - name: Remove SMTP Relay
    ansible.builtin.lineinfile:
      path: /etc/postfix/main.cf
      regexp: '^relayhost'
      state: absent

  - name: Set SMTP Relay
    ansible.builtin.lineinfile:
      path: /etc/postfix/main.cf
      regexp: '^relayhost'
      line: relayhost = [mta.karlsbakk.net]:26
    notify:
      - reload postfix

  handlers:
    - name: reload postfix
      ansible.builtin.systemd:
        name: postfix
        enabled: true
        state: reloaded

