# vim:ts=2:sw=2:sts=2:et:ai

- hosts: ubuntu-servere
  strategy: free
  remote_user: root

  tasks:
  - name: Disable IPv6 tempaddr
    ansible.builtin.lineinfile:
      path: "/etc/sysctl.d/10-ipv6-privacy.conf"
      regex: "net.ipv6.conf.{{ item }}.use_tempaddr"
      line: "net.ipv6.conf.{{ item }}.use_tempaddr = 0"
    with_items:
      - "{{ ansible_interfaces }}"
      - 'default'
      - 'all'
