# vim:ts=2:sw=2:sts=2:et:ai:fdm=marker:isfname-==:isfname-=,

- hosts: update_and_reboot_if_needed
  strategy: free
  remote_user: root
  tasks:
  - name: Update apt-cache and do dist-upgrade
    apt:
      update_cache: yes
      cache_valid_time: 3600
      upgrade: dist

  - name: Check if reboot required
    stat:
      path: /var/run/reboot-required
    register: reboot_required_file

  - name: Reboot if required
    reboot:
    when: reboot_required_file.stat.exists == true
