# vim:ts=2:sw=2:sts=2:et:ai:fdm=marker

# - hosts: zabagt2
#   strategy: free
#   remote_user: root
#   tasks:
#   - name: Add backports
#     ansible.builtin.copy:
#       src: files/etc/apt/sources.list.d/backports.list
#       dest: /etc/apt/sources.list.d/backports.list

- hosts: vmer
  strategy: free
  vars:
    http_port: 80
    max_clients: 200
  remote_user: root
  tasks:
  - name: Replace sources.list with a sane one
    ansible.builtin.copy:
      src: files/etc/apt/sources.list
      dest: /etc/apt/sources.list
      backup: yes
      owner: root
      group: root
      mode: 0644

  - name: Add backports
    ansible.builtin.copy:
      src: files/etc/apt/sources.list.d/backports.list
      dest: /etc/apt/sources.list.d/backports.list
      owner: root
      group: root
      mode: 0644

  - name: apt-get full-upgrade
    ansible.builtin.apt:
      update_cache: yes
      upgrade: dist
      autoremove: yes

  - name: Install the normal stuff
    ansible.builtin.apt:
      name:
        - apt-transport-https
        - bc
        - curl
        - etckeeper
        - fail2ban
        - git
        - htop
        - locales-all
        - lshw
        - mlocate
        - nfs-common
        - pastebinit
        - pwgen
        - sudo
        - sysstat
        - tmux
        - tshark
        - ufw
        - uptimed
        - vim
      state: latest

  - name: Enable sysstat
    ansible.builtin.lineinfile:
      path: /etc/default/sysstat
      regexp: '^ENABLED='
      line: 'ENABLED="true"'
    notify:
      - restart sysstat
      - updatedb
  - name: Make sure roy is member of sudo
    ansible.builtin.user:
      name: roy
      group: sudo
  - name: update /root/.tmux.conf
    ansible.builtin.blockinfile:
      dest: /root/.tmux.conf
      block: |
        set -g prefix C-a
        unbind-key C-b
        bind-key C-a send-prefix
        setw -g mode-keys vi
      create: yes
  - name: Add relevant keys to \$HOME/.ssh/authorized_keys
    ansible.builtin.blockinfile:
      path: '{{ item.filename }}'
      create: yes
      owner: '{{ item.owner }}'
      group: '{{ item.group }}'
      block: |
        ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDHgvHmjGfZgw1tT3zC88dPWEH+mxykfGvE+S8atcfdAl/3Zjcp48UGk0otL4v+9rdIo1/PwOL/aUR3D19GyQtWycO32wyNNr6N5DQNo64YAfI6unxLceiRWqWEEhEHSfKbVVjUyQllhjhzoyLxQ7OMBVVdIbTFRqAYIKXnLDD9uuC6fpcGTGDEc28Y3gz1Q1i3D55bIXF5Usd1BSP3D2FRgjDRX+0xGCvavWG548p1Y0tbbWbL+t+gXbHwRQtg2eqcd5nM1QdS0EX/r/9eOu715UMtiSk+NW6I8PzJN/KmO9PxJ9KLKOtBYfx4kXGVPk3e4O8ZpExHa4e4nzwYibCv roysk@oslomet.no
        ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCqbzUA7TXuzcYjHnWEA5uWOJfLAUqzTQnDi9HATYeg5xTNoUZ53gkUS2vUK1mpHDWUM7twXiVN9PFKuQHDVC7t2A3xCzi3RVRoLJhOpV3pSGtYRLClWP5SoAzgE0G6kOtRyWjzUKoEm6kL4sOSCHfIloXnrU1+9PbB0bBCdMTA0XBSMYwxvt5HbWJp3T3cqsjdz9OVihZ21thvEHLRSDkcEUcSBpyuxiCpi3xX4hNd5Ek4KgnbktyqqPsTYHIxaBA0wCaRODyqInFmgqGjCtvDOB/IXl1KXHhxngWHuUd1O+Q+OXizVcICsaNLjEDc46XEwTAFT5KfjRWG+Vty1iiX root@smilla.karlsbakk.net
        ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAvlfCc6RoDq7jzSy1svNMPcusSkCMefCZE6aT12I7KgPOXUdvGfPqexZhMEO0ooW9+hIwa0NXozEB39Wl8QonsMNtkaJ68KnLAzh6acEFfhzBlSMgjh8EFErD9Td3MFOEZlPApwgIc4H1P7pmhAri3rYN2kWkcD1M2yATMsa7g7PSM9Lq4ol65lf7pFtk/KP6jW5g9HCR0lXllX1RCMCv3iozd8eUApatP3SmkY4UIChPrhefbOrdDIevTxjL7LKXo8Ojv3qbu2H34NdI+y6JDZh9SWJZNIE0bSj9FnO0ZlYXigL2z+xgqfpNSMXnuYc0/zPyot0dLYLFRFhSBjUYnQ== roy@karlsbakk.net
        ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCsWphX2V5mwtwpEYA8SMC0jsIyRIP2CR3aD7Wf6lrIgiNZvrPM8JzvxMhUctpKL1asULV0yyJMQDjFJ2G2mwDz0ejVPo5JMgIPdnsPS7raX8yejXPEcRsoCE0nYTcvHo6JFhy0zJNEQgtJJgpHTs4QmkPQRwqUUplTl7hE1V1We63Zjws5dJpnfErGHy6gEEVxd0fVwxDHCdG2/h6MrVv9zfFCc60tYY03yQZlTGma7ZEUILl8jPv6B63PTFWaXGM9uv+0gPb4Z4WocNany2J5pctIXJes0l/9/I0J9o+LtF9Hl1JXIDrYMg8HytQOh9yvKSupB9Qe3IMh9XrgU3/v roy@smilla.karlsbakk.net
    with_items:
      - { filename: '/root/.ssh/authorized_keys', owner: 'root', group: 'root' }
      - { filename: '/home/roy/.ssh/authorized_keys', owner: 'roy', group: 'roy' }
      
  - name: update/create ~/.vimrc
    ansible.builtin.blockinfile:
      dest: '{{ item.filename }}'
      create: yes
      owner: '{{ item.owner }}'
      group: '{{ item.group }}'
      marker: '" {mark} ANSIBLE MANAGED BLOCK'
      block: |
        set modeline
        set modelines=5
        set incsearch
        set nohlsearch
        syntax on
        set background=dark
        set ruler
        set mouse=
        set ttymouse=

        if has("autocmd")
          au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
          filetype plugin indent on
        endif

        \" ABEL
        au BufNewFile,BufRead *.gcode setf gcode
        let g:autoclose_on = 0
        let g:AutoPairs = {}
    with_items:
      - { filename: '/root/.vimrc', owner: 'root', group: 'root' }
      - { filename: '/home/roy/.vimrc', owner: 'roy', group: 'roy' }

  - name: update /home/roy/.bashrc
    ansible.builtin.blockinfile:
      dest: /home/roy/.bashrc
      create: yes
      block: |
        # Ansible was here!!!!
        export LS_OPTIONS='--color=auto -F'
        eval "`dircolors`"
        alias ls='ls $LS_OPTIONS'
        alias l='ls $LS_OPTIONS -l'
        alias df='df -x tmpfs -x devtmpfs'

        set -o vi

        [ -f $HOME/.aliases ] && source $HOME/.aliases

  - name: update /root/.bashrc
    ansible.builtin.blockinfile:
      dest: /root/.bashrc
      create: yes
      block: |
        # Ansible was here!!!!
        export LS_OPTIONS='--color=auto -F'
        eval "`dircolors`"
        alias ls='ls $LS_OPTIONS'
        alias l='ls $LS_OPTIONS -l'
        alias df='df -x tmpfs -x devtmpfs'

        set -o vi
        export EDITOR='vi'

        [ -f $HOME/.aliases ] && source $HOME/.aliases

  - name: set timezone to Europe/Oslo
    timezone:
      name: Europe/Oslo

  - name: UFW - Allow ports
    ufw:
      rule: 'allow'
      port: '{{ item.port }}'
      proto: '{{ item.proto }}'
      comment: '{{ item.comment }}'
    with_items:
      - { port: '22', proto: 'tcp', comment: 'Allow SSH' }

  - name: UFW - Allow to
    ufw:
      rule: allow
      to_ip: '{{ item.ip }}'
      comment: '{{ item.comment }}'
    with_items:
      - { ip: '224.0.0.0/4', comment: 'Allow IPv4 Multicast' }
      - { ip: 'ff00::/8', comment: 'Allow IPv6 Multicast' }

  - name: UFW - Allow from 
    ufw:
      rule: allow
      from_ip: '{{ item.ip }}'
      comment: '{{ item.comment }}'
    with_items:
      - { ip: '192.168.10.0/23', comment: 'Allow from local network (IPv4)' }
      - { ip: '2a01:79c:cebf:61e4::/62', comment: 'Allow from local network (IPv6)' }

  - name: UFW - Allow UDP traffic for mosh
    ufw:
        rule: allow
        port: 60000:60049
        proto: udp
        comment: Allow mosh traffic

  - name: Enable UFW and disable logging
    ufw:
        state: enabled
        logging: "off"

  - name: Creates an entry like "PATH=/opt/bin" on top of crontab
    cron:
        name: PATH
        env: yes
        job: /sbin:/usr/sbin:$PATH
        state: present

  - name: Crontab for fstrim - daily
    cron:
      name: "fstrim for everything supported @ 01:00"
      minute: "0"
      hour: "1"
      job: "fstrim -a"
      state: present

  - name: Crontab for fstrim at bootup
    cron:
      name: "fstrim for everything supported @reboot"
      special_time: reboot
      job: "fstrim -a"
      state: present

# - name: Zabbix Agent2
#   ansible.builtin.import_playbook: zabbix-agent2.yaml

  handlers:
    - name: restart sysstat
      ansible.builtin.systemd:
        name: sysstat
        enabled: yes
        state: restarted

    - name: updatedb
      command:
        cmd: /usr/bin/updatedb

          # name: Import zabbix-agent2 playbook
          # ansible.builtin.import_playbook: zabbix-agent2.inc.yaml

