# vim:ts=2:sw=2:sts=2:et:ai:fdm=marker:isfname-==:isfname-=,

- hosts: zabagt2
  strategy: free
  remote_user: root
  tasks:
# Add zabbix key {{{
#
# - name: Add zabbix key
#   ansible.builtin.copy:
#     src: files/etc/apt/trusted.gpg.d/zabbix-official-repo.key
#     dest: /etc/apt/trusted.gpg.d/zabbix-official-repo.key
#     owner: root
#     group: root
#     mode: 0644
#
# }}}
  - name: Add zabbix GPG key
    ansible.builtin.copy:
      src: files/etc/apt/trusted.gpg.d/zabbix-official-repo-apr2024.gpg
      dest: /etc/apt/trusted.gpg.d/zabbix-official-repo-apr2024.gpg
      owner: root
      group: root
      mode: 0644

  - name: Add zabbix APT list
    ansible.builtin.copy:
      src: files/etc/apt/sources.list.d/zabbix.list
      dest: /etc/apt/sources.list.d/zabbix.list
      owner: root
      group: root
      mode: 0644

  - name: apt-get full-upgrade
    ansible.builtin.apt:
      update_cache: yes
      upgrade: dist
      autoremove: yes

  - name: Install zabbix-agent2
    ansible.builtin.apt:
      name:
        - zabbix-agent2
      state: latest

  - name: Remove old zabbix-agent
    ansible.builtin.apt:
      name: 
        - zabbix-agent
      state: absent

  - name: UFW - Delete old zabbix traffic from zabbix
    community.general.ufw:
      rule: allow
      from_ip: "{{ item.ip_addr }}"
      proto: "{{ item.proto }}"
      port: "{{ item.port }}"
      comment: "{{ item.comment }}"
      delete: true
    with_items:
      - { ip_addr: '77.40.158.123', proto: 'tcp', port: '10050', comment: 'Allow zabbix traffic from zabbix.karlsbakk.net (IPv4)' }
      - { ip_addr: '2001:8c0:9302:4::123', proto: 'tcp', port: '10050', comment: 'Allow zabbix traffic from zabbix.karlsbakk.net (IPv6)' }
      - { ip_addr: '193.29.58.196', proto: 'tcp', port: '10050', comment: 'Allow zabbix traffic from zabbix2.karlsbakk.net (IPv4)' }
      - { ip_addr: '2a0a:51c0:0:1f:4ca5::2', proto: 'tcp', port: '10050', comment: 'Allow zabbix traffic from zabbix2.karlsbakk.net (IPv6)' }
      - { ip_addr: '80.213.160.61', proto: 'tcp', port: '10050', comment: 'Allow zabbix traffic from zabbix.malinux.no (IPv4)' }
      - { ip_addr: '2001:4641:4dfa::2ab1', proto: 'tcp', port: '10050', comment: 'Allow zabbix traffic from zabbix.malinux.no (IPv6)' }

  - name: UFW - Allow zabbix traffic from zabbix
    community.general.ufw:
      rule: allow
      from_ip: "{{ item.ip_addr }}"
      proto: "{{ item.proto }}"
      port: "{{ item.port }}"
      comment: "{{ item.comment }}"
    with_items:
      - { ip_addr: '2.58.14.136', proto: 'tcp', port: '10050', comment: 'Allow zabbix traffic from zabbix.karlsbakk.net (IPv4)' }
      - { ip_addr: '2a07:efc0:1001:bcb0::2', proto: 'tcp', port: '10050', comment: 'Allow zabbix traffic from zabbix.karlsbakk.net (IPv6)' }

  - name: Copy plugins
    ansible.builtin.copy:
      src: 'files/usr/local/bin/{{ item.filename }}'
      dest: '/usr/local/bin/{{ item.filename }}'
      owner: root
      group: root
      mode: 0755
    with_items:
      - { filename: 'check-dns.sh' }
      - { filename: 'zabbix_check_linux_updates.sh' }
      - { filename: 'zabbix_check_needs_reboot.sh' }
      - { filename: 'zabbix_checkro.pl' }
      - { filename: 'zabbix_linux_distro_check.pl' }
      - { filename: 'zabbix_kernelversioncheck.sh' }
      - { filename: 'smartctl-disks-discovery.pl' }

  - name: Create custom Zabbix agent config
    ansible.builtin.blockinfile:
      path: /etc/zabbix/zabbix_agent2.d/karlsbakk.conf
      block: |
        # vim:isfname-==:isfname-=,

        # General settings
        Server=2a07:efc0:1001:bcb0::2
        ServerActive=2a07:efc0:1001:bcb0::2

        Hostname={{inventory_hostname}}
        Timeout=30

        # Distro plugin
        UserParameter=custom.distro.name,/usr/local/bin/zabbix_linux_distro_check.pl --name
        UserParameter=custom.distro.version,/usr/local/bin/zabbix_linux_distro_check.pl --vers
        UserParameter=custom.distro.arch,/usr/local/bin/zabbix_linux_distro_check.pl --arch
        UserParameter=custom.distro.friendlyname,/usr/local/bin/zabbix_linux_distro_check.pl --friendly

        # Reboot check
        UserParameter=custom.rebootcheck,/usr/local/bin/zabbix_check_needs_reboot.sh --local

        # Update check
        UserParameter=custom.yumupdatescheck,/usr/local/bin/zabbix_check_linux_updates.sh

        # Read only check
        # UserParameter=custom.fsrocheck,/usr/local/bin/zabbix_check_fs_ro.pl
        UserParameter=custom.fsrocheck,/usr/local/bin/zabbix_checkro.pl
        UserParameter=vfs.fs.discovery_custom,/usr/local/bin/zabbix_check_fs_ro_lld.pl

        # Kernel updates
        UserParameter=custom.kernelversioncheck,/usr/local/bin/zabbix_kernelversioncheck.sh --local

        # Check if server can do DNS lookups
        UserParameter=custom.dnslookup,/usr/local/bin/check-dns.sh google.com

        # Check if mountpoint is actually mounted
        UserParameter=vfs.mount.is_mounted[*],mountpoint -q $1 && echo YES || echo NO

        # SMART
        UserParameter=uHDD.get[*],sudo smartctl -i -H -A -l error -l background $1 || true
        UserParameter=uSSD.get[*],sudo smartctl -i -H -A -l error -l background $1 || true

        UserParameter=uHDD.discovery[*],sudo /usr/local/bin/smartctl-disks-discovery.pl -i $1
        UserParameter=uSSD.discovery[*],sudo /usr/local/bin/smartctl-disks-discovery.pl -i $1

      create: yes
    notify:
    - restart zabbix_agent2

  handlers:
    - name: restart zabbix_agent2
      ansible.builtin.systemd:
        name: zabbix-agent2
        enabled: yes
        state: restarted
